name: Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.prerelease }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['7.3', '7.4']
        dependency-version: [prefer-lowest, prefer-stable]
        prerelease: [false]
        include:
          - php: 8.0
            os: ubuntu-latest
            dependency-version: prefer-lowest
            prerelease: true
          - php: 8.0
            os: ubuntu-latest
            dependency-version: prefer-stable
            prerelease: true

    name: PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2
        coverage: none

    - name: Setup Problem Matches
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Install PHP 7 dependencies
      run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress
      if: "matrix.php < 8"

    - name: Install PHP 8 dependencies
      run: composer update --${{ matrix.dependency-version }} --ignore-platform-req=php --no-interaction --no-progress
      if: "matrix.php >= 8"

    - name: Unit Tests
      continue-on-error: ${{ matrix.prerelease }}
      run: vendor/bin/pest --colors=always
